### ISSUE TITLE
Logarithmic scales

### ISSUE THREAD

**Issue by jo-moeller** [European-XFEL/EXtra-foam#156]
Changing the axis scales via right click/plot options/transforms/log X or log Y is not changing actually the axis to a log scale. It looks like it is only changing the lable but not the plot itself.
Two plots for comparison:
with linear y axis:
![linear](https://user-images.githubusercontent.com/57397797/78907332-d7043080-7a80-11ea-8d16-38b8f9569a62.PNG)

with log y axis:
![log](https://user-images.githubusercontent.com/57397797/78907376-e4b9b600-7a80-11ea-9030-1c188de2fc13.PNG)

For certain data, we need this logarithmic scale for example in the disply of the azimuthal integration or the histograms.

The same run would look something like this on a log-log plot (averaged over many trains and pulses, but still. just for comparison)
![grafik](https://user-images.githubusercontent.com/57397797/78907487-0f0b7380-7a81-11ea-87f6-799e24a7dff8.png)

**Comment by zhujun98** [comment]
The right-click menu is from the implementation in `pyqtgraph` and we already know there is some problem with the log scale. To be frankly, we have not tested all the functionalities in the right-click menu since in most cases people only use `auto scale` and probably `invert Y`. 

There is a plan to refurbish the right-click menu. But it will need to dig deep into the `pyqtgraph` code.  I will put this into priority. But in case you will need it for some commissioning or user experiment, it can be easily add just for azimuthal integration.

**Comment by jo-moeller** [comment]
Hi, just back from vacation, so sorry for the late reply. The log-scale would be more crucially needed for the histograms rather than the azimuthal integration plot. And there are some user experiments in the pipeline, where we would need that. But as it is also not clear, when those will happen, I guess we can wait for a proper refurbishement and don't need a quick-and-dirty solution.

**Comment by zhujun98** [comment]
OK! This is something to be prioritized since many users have "complaint" about it :-)

**Comment by zhujun98** [comment]
@jo-moeller Problem finally solved! Logarithmic scale can still be activated in the context menu. It does the following operation on the original data:

```py
        ret = np.nan_to_num(arr)
        ret[ret < 0] = 0
        return np.log10(ret + 1)
```

In the future, it is also possible to add a "conversion policy" combo box to allow selecting among different conversion policies.

I will deploy it (0.9.0beta2) in EXtra-foam/beta and EXtra-foam/alpha later today. 0.9.0 will be released next week and deployed in EXtra-foam/beta.
